### ISSUE TITLE
Phase IV meta-issue

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc#104]
*Phase IV ended and the new issues are now being tracked on #105.  This issue is no longer updated, but kept around for reference.*

-----

## Phase IV
The principal objectives of this phase of development (July - December 2020) is to:
a) Improve fidelity and accuracy of the model
b) Expand the real-world simulation of SIMOC from Mars to the Moon - MAYBE ?
c) Improve the user experience with a simplified Dashboard - DONE
d) Improve the user experience with few panels and/or features within the existing panels - DONE

### BACK-END / SERVER-SIDE

**Low Hanging Fruit**
- [x] **Remove value in front of label** - MIGHT BE COMPLETE; NEED TO TEST
- Re-discovered that units are set as "1.0 kg" instead of just "kg"; so
- Iurii to investigate revising this to a unit label only (sans "1.0")

- [x] **Add agent name and abbreviation to JSON** - INCOMPLETE; NEED TO INVESTIGATE
Agent name is being sent from the server; and Ezio is currently reformatting on the fly; so need to add proper name **and** abbreviation to the JSON. Ezio is not in need of this now, as he is hard-coding this on the front-end. We can return to this later. However, when we come back to this, we can rebuild the system for higher efficiency with a single, first-time transfer of the names only.

**Mid Hanging Fruit**
- [ ] **Start at Zero** - INCOMPLETE 
Start Dashboard at time step 0 instead of 1. This is an easy change, but could have big consequences. Iurii needs to be sync with Ezio. 
 - This is either a change to the database, or a manual introduction of all the values at timestep zero [Config Wizard + agent_desc + hard coded values].
 - It is important to provide these initial values in the same format at the rest, such that it is seamless for the users who download their data.
 - Let's do this manually, for now, and then in the future take the output of this initial effort and populate the db instead.

- [x] **Rations -vs- Harvested Food**
In Phase IIIb, 'biomass_total' is the full plant mass while growing and at harvest. When harvested, 'biomass_total' is split into edible (a given quantity in agent_desc) and inedible (not calculated nor stored at this time). This is done in the code, but not in the agent_desc.

For example, see the agent 'rice':
'biomass_totl': 0.001259583 x 2040 = 2.5695432 kg
'food_edbl': 0.77095 kg edible at harvest
(inedible): 2.5695432 - 0.77095 = 1.7985932 kd inedible at harvest

In Phase IV, we need to differentiate 'rations' from 'food' such that 'edible_biomass' moves from harvest to 'food' such that 'rations' will only go down (until the point at which we introduced resupply missions). So, we need to modify the agent_desc.json to put the edible portion of the harvested plants into 'biomass_edible'.

Kai's suggestion is to leave the current transfer from 'biomass_total' to 'food_edbl' alone. This is fine. Instead, we need to add a new category called 'food_rtns' into which the rations are placed at the start of the mission, so the dashboard we will see "Rations" and below it "Food". 

The challenge is in setting a priority such that human agents eat 'food_edbl' first and then look to 'food_rtns' as a secondary source. At the start of the mission, and until first harvest, 'food_edbl' will be empty so only 'food_rtns' will be consumed.

- Define the human agent as able to eat from either, with a priority for edible biomass over food rations

(this is where we stopped reviewing tasks on 2021 02/14)

- [ ] **Logging Panel**
Build logging panel: "Crop [plant] has been harvested", "Water is at a critical low", "Battery is fully recharged"
Iurii can send the log updates (at the ABM level) and Ezio can determine the subjective evaluation on the front-end.

**Fruit high on the Tree (requiring a ladder and a chain saw)**
- [ ] **01 - Mars and Moon**
- Offer both Moon and Mars as destinations for SIMOC habitats
- Update solar PV panels for Mars (1/2 instead of 1/3 of Earth)
- Update solar PV panels for Moon (at the equator) with full power and 14 days illumination followed by 14 days dark
- Add solar PV panels for the Moon (at the South pole) with full power and constant light (no dark)
- Add values for radioisotope thermoelectric generator (https://en.wikipedia.org/wiki/Radioisotope_thermoelectric_generator), which will be our second power source (in addition to PV)
- Offer a position at the a) equator or b) South pole of the Moon
- Option to combine solar PV + thermoelectric generator

Consider giving the user trade-offs of solar PV + battery vs thermoelectric generator

- [ ] **02 - Elemental Model Validation**
- (Ezio to prepare a description and insert here)

- [ ] **a - Hard transaction connections**
This is difficult at this time, but it is a MUST HAVE for the overall update of currency tracking
- must have an IN to have an OUT (e.g. water in vs urine out)
- if one element is not available, will not consume another

- [ ] **b - Deprivations - Human Nutrition**
At this point in time, if an inhabitant goes 15 days without food, and then consumes a single strawberry, the food clock is reset to 0.  Clearly, this does not make sense. We need to introduce even a basic,per human agent nutrient tracking for overall health status. Kai, Ezio, and Iurii need to discuss how to do this; and maybe consult a nutrionist. This will compliment a higher fidelity for plant physiology.
- How does this impact connections?

- [ ] **c - Deprivations - Refined plant growth**
We need to introduce a more refined model for how plants are affected by a lack of water, CO2, or light that is **not** binary, rather takes into account the amount of deprivation, the duration of deprivation, and how much of the missing currency(ies) are recovered in the subsequent time frames.

- [ ] **d - Connections between outputs and storages**
- currently, cannot connect outputs to specific storages
- currently, all storages are treated equally
- e.g. cannot create an agent that will consume air from one storage and move it to another

### ITEMS FOR EZIO

- [ ] **Deprivations Display**
Display current number of days without Food and Water needs to be tracked / sent to the front-end
Requires that the deprivation values be sent to the front-end; Ezio will look into this 20210106

- [ ] **Mouse Hoover**
Add 'mouse hoover' for all CW and Dashboard buttons for more direct, obvious feedback

- [ ] **Inhabitants Status**
Replace mouse hoover with (i) icon or add mouse hoover 'tool tips' to many items across all panels (see Inhabitant Status for an existing example

- [ ] **Panel revisions**
(see meeting minutes from January 6, 2021)

### ITEMS FOR KAI

- [ ] **01 - Deprivations Update**
- Kai to get with Jennifer Fogarty at NASA JSC to discuss this; then come back to the team with logic
- Kai to get with Murat, Gene at UA CEAC to discuss this; then come back to the team with logic

### OTHER ITEMS

- [ ] **Agent Interaction Map**
Build a graphical map, on the fly, once the configuration is built and present to the user on the Dashboard or as a download.

- [ ] **Expose more data**
Expose more data to user - sending the data is easy - building the new panels takes some effort - may affect the overall performance
==> Kai, Ezio, Iurii need to review current data -vs- potential new data and then determine which will be exposed, and how

### COMPLETE

- [x] **Preset Updates**
Per the email with Subject "Changes":

1) With the Full Garden preset, reduce solar to 300
2) In the JSON, I changed the activation for the dehumidifier to 2%
3) Min/Max values:

 Parameter Minimum / Maximum Values
 Duration: 10 min / max 365 Earth days
 Inhabitants: 0 min / max 10 astronauts
 Food: 0 min / max 5475 kg [0.0625 kg/hr x 24 hrs x 365 days x 20 astronauts max]
 ECLSS: 0 min / max 4 [supports maximum 3 astronauts per module]
 Solar PV: 0 min / max 100 [354 W/m2 , given a 1x2m panel on Mars]
 Batteries: 0 min / max 10,000 kWh

> 8760 is the old 1.0 kg value. The new 0.0625 results in 5475 kg, or 6000
> even. That said, we could leave it higher, even 10,000 so that if their
> crops fail they don't starve. I had not thought of that.
>
> We could reduce life support to just 3 or 4, to match the limit of 10
> humans. What do you think? Or maybe we wait until I have met with
> Paragon and adjusted all the functions.
