### ISSUE TITLE
Phase V meta-issue

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc#105]
### Partially complete Phase IV items (see #104)
- [x] #141
  - Remove value in front of label (see 2da1e4b)
  - Add agent name and abbreviation to JSON  (see 2da1e4b)
  - #122

- [ ] Start at Zero (see 2da1e4b)

### Other Phase V projects (in no particular order)
- [ ] #142 and update the Inhabitants status panel, showing:
  - The wellness index of the humans
  - How long theyhave gone without food/water

- [ ] Improve Greenhouse panels to show both soil usage % and growth %
  - https://github.com/kurkle/chartjs-chart-treemap
  - https://github.com/kurkle/chartjs-chart-matrix
  - See `[simoc] meeting minutes: 2021 01/04b - TODOs`

- [ ] Validation and Tracking (see also #128):
  - [ ] Elemental Validation: make sure inputs/output for each agent match at the element level
  - [ ] Elemental Tracking: track elements throughout the system
  - [ ] Nutrition Tracking: track food macronutrients (carbohydrates, fats, proteins) (see #161)
  - [ ] Calories Tracking: track calories and heat (see #153)

- [ ] #128 
  - allow agents to have multiple separate inputs (or outputs) that exchange the same currency (e.g. get electricity from two sources)
  - as above but with different currencies (e.g. getting food from rations or harvested plants)
  - implement priorities for inputs/outputs
  - #134 

- [ ] Food/plants-related improvements
  - [x] #111 
  - [ ] Composting
  - [x] Staggered planting and harvesting (also within the same cultivar -- e.g. harvest a row of tomatoes per week)

- [ ] Human-related improvements
  - [ ] #126 
  - [ ] #112 
  - [ ] #352 

- [ ] Partial step data calculation
  - [ ] Prediction-based (current, scientific);
  - [ ] Turn-based, mid-simulation mitigations (future, game-play)

- [ ] #160 and randomness
  - [x] Incorporate the "entropy engine" for random fluctuations (already in the code?)
  - [ ] #124

- [ ] Custom connections and connection graph
  - provide a GUI for users to connect agents/storages
  - show a static connection map
  - show a dynamic exchange map (ties into Elemental Validation)

- [ ] Separate ECLSS modules into components (Sean Gellenbeck)

- [ ] #143
  - [ ] Additional power generation (needed before we add the Moon)

- [ ] Infrastructure-related improvements
  - [x] #140 
  - [x] #129 
  - [ ] #138 

See also `[simoc] meeting minutes: 2021 09/15`.
