### ISSUE TITLE
Phase VII meta-issue

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc#107]
**High-priority**
- [ ] Videos for SIMOC and SIMOC-ABM
- [ ] Support mobile/tablet on simoc-web
- [ ] Huge value unlock for the amount of work, Also discussed an agent store
  1. Route, View, Landing Page (mostly done?)   
  2. Get skeleton form: text input, checkbox...   
  3. Navigation/Layout (involve Kai)- Connections diagram with [GoJS](https://gojs.net/latest/samples/dynamicPorts.html): (If includes all agents, very complex, hard to see)
  4. From Dashboard, maybe just show one agent's inputs/outputs (non-editable). From AgentEditor, maybe show more? (editable)   
  5. Original diagram of SIMOC: https://simoc.space/simoc/advanced-user/ 
- [ ] Get rid of hardcoded labels and units by using DashboardStore.currencyDict
- [ ] CI/CT (test automation) for simoc-abm
- [ ] Humans change colors when sick (below threshold, deprive <max)- Create logs on frontend from data objectSoylent Green Easter Egg

**Possible, low-hangingImplement Wellness Index**

- [ ] Build on granular health/status updates- New value related to humans showing overall well-beingUpdate HumanAgent Model to Randomize Thresholds- Have slight variation in thresholds and deprive values to everyone doesn't die at once- A bit involvedLogging Panel
- [ ] Calculate and record important events from simoc-abm: harvesting plants, human low on food, etc.
- [ ] Agents have a ‘threshold’ currently, but only results in death
- [ ] Implement as dict of bools, or a list of logs by step
- [ ] **Could do a very simple implementation frontend-only**

Zero-Based Indexing 
- [ ] Currently simoc-web starts at step ‘1’. This means (1) we don’t show the initial state, (2) records have to be 1-shifted.
- [ ] simoc-abm is setup to start with step 0, just need to flip a flagImprove Greenhouse Panels
- [ ] Add chartJS specific visualizations, more clear
Composting
Human Flow Improvements 
- [ ] Breathing in and out with some absorption
- [ ] More specific breakdown of urine/feces/food makeup
Visualize Connections as a Graph (go-js)
Separate ECLSS module into components (frontend)
Add the moon

**Possible, but difficultElemental Validation**
- [ ] Track nutrients, heat…
Vary human flows by time-of-day, activity, metabolic rate, mass, etc.
Reconciling SAM and SIMOC
- [ ] Convert sensor readings to mass (kg)
- [ ] SAM has configuration screen
- [ ] Ezio rewrite from scratch? Lots of external packages we can use
- [ ] Some unnecessary frontend duplication

C or D?Slim Installation? W/o Docker, Celery, etc.Machine Learning Prediction

**Unlikely in next 12mo**
- [ ] Mid-Sim Adjustments (frontend) (would be super cool, but change the raison-d’etre?)
Entropy
- [ ] Removed in simoc-abm
Bridge between V-HAB and SIMOC
- [ ] Permissions?
- [ ] Probably really hard, but possible
