### ISSUE TITLE
NatGeo Launch meta-issue

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc#110]
Items for Iurii:
- [ ] **Biomass vs Food**
The values for biomass_totl and food_edbl are incorrect.  See #111 

- [ ] **Human Water versus Urine**
Need to determine how urine and solid waste are produced when water/food is scarce.  See #112 

- [ ]  **CO2 removal agents NOT working as expected**
CO2 Removal Sawd and CO2 Reduction Sabatier are not activated correctly.   See #113 

- [ ] **Sim crashes when Agent Dies**
Whenever any agent dies (human, plant) the simulation crashes for that user. See #114 

- [ ] **User not found after login**
Sometimes the server can't find the logged user while trying to start a new game.  See #115 

Items for Ezio:

- [x] **Do a release once everything else is fixed**

- [x] **Update beta with logo and updated wiki**
- [x] **Add back sabatier and add CH4 removal agent**

- [x] **Limit humans to 10**

- [x] **Limit sims to 1 year**
- Liimit the days to 360
- Limit the food to 17520 kg
- Remove the last two columns from the food table in the wiki
- Update the server with max 10000 steps

- [x] **Intercept browser refreshes**
Show a warning when the user tries to refresh the page.
- [x] **Redundant names in Mission Config Panel**
Duration Length: ==> Duration
Crew Quarters: Crew Habitat Small ==> Small
Greenhouse: Greenhouse Small ==> Small

- [x] **Remove drop shadow**
Remove drop shadow from Config Wiz and Dashboard

- [x] **iframe is on hold as Sarah at Nat Geo is unable to get it to work on her end**
Ezio has been guiding Sarah as to how to improve the i-frame configuration for a fullscreen experience; we are now waiting for Sarah to test the latest code sent by Ezio
**used an external link instead**

Other issues:
- [x] **Update presets**
Kai, Ezio

- [ ] **Plant Water Vapor**
NASA plant data has no entries for water vapor produced by the plant. So, in SIMOC we have only water vapor produced by the humans. However, the plant biomass is principally water, so that water is stored as biomass (meaning the plant is a temp storage agent) and when the plant is harvested, that water is in food_edible. When the human eats it, it is returned to the system as h20_waste which is processed back into water.
==> NEED TO VALIDATE --Kai, Ezio
